# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/34b254c1-998d-4124-8a27-8e5bedf081c5";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/34b254c1-998d-4124-8a27-8e5bedf081c5";
      fsType = "btrfs";
      options = [ "subvol=@swap" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/34b254c1-998d-4124-8a27-8e5bedf081c5";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/storage" =
    { device = "/dev/disk/by-uuid/cce9013d-2dce-43bc-9012-d729a2359243";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A883-823C";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
